name: Build and Release Theme

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Zip theme files
        run: |
          THEME_NAME="soymichelero"
          ZIP_NAME="${THEME_NAME}-$(echo $GITHUB_REF | sed 's/refs\/tags\///').zip"
          zip -r $ZIP_NAME . -x '*.git*' -x '.github/*'

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: "soymichelero-*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}